### ISSUE TITLE
Example of box staying the same size regardless of zoom like original Marker

### ISSUE THREAD

**Issue by kevinsimper** [googlemaps/js-three#110]
The google.maps.marker stays the same size regardless of how zoomed in or out the map is.

How can the same effect be archived?

Add a box or gltf can become invisible if the users is zoomed to far our or in.

**Comment by kevinsimper** [comment]
I made a hack that works by using the bounds of the map, and then calculating a initial size of the bounds with a start scale and then animating it based on that. Super rough, but it archives it. I first thought of using the zoom level, but since it is a number between 18 and 5, and I don't know if it is linear, I was not sure about that solution.

![2021-09-28 19 18 07](https://user-images.githubusercontent.com/1126497/135134797-cb188710-63c1-4d84-850e-078410c3cdc6.gif)

vs normal google maps js-three

![2021-09-28 19 19 07](https://user-images.githubusercontent.com/1126497/135134965-7d353520-3db2-4c2a-8480-a5950e04b097.gif)


https://codesandbox.io/s/unruffled-yalow-7c7dk?file=/src/index.ts

**Comment by jpoehnelt** [comment]
>zoom level, but since it is a number between 18 and 5, 

Should be able to use zoom to scale the object as the map changes. The zoom should follow a pattern similar to the following:

20 : 1128.497220
19 : 2256.994440
18 : 4513.988880
17 : 9027.977761
16 : 18055.955520
15 : 36111.911040
14 : 72223.822090
13 : 144447.644200
12 : 288895.288400
11 : 577790.576700
10 : 1155581.153000
9  : 2311162.307000
8  : 4622324.614000
7  : 9244649.227000
6  : 18489298.450000
5  : 36978596.910000
4  : 73957193.820000
3  : 147914387.600000
2  : 295828775.300000
1  : 591657550.500000

**Comment by kevinsimper** [comment]
@jpoehnelt Thank you, did not know that, that is better 😄
