### ISSUE TITLE
Enable casting Shadows

### ISSUE THREAD

**Issue by YosanAI** [googlemaps/js-three#185]
I want to cast shadows of objects on the map (ground) and on other objects in the threejs scene. 

in the meantime, is there any workaround to cast/receive shadows?

**Comment by YosanAI** [comment]
@jpoehnelt here is an example that is set up for shadow but doesn't work.

`import { AmbientLight, DirectionalLight, Scene,Mesh,PlaneGeometry,MathUtils,MeshPhongMaterial,DoubleSide, Vector2} from "three";

import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { ThreeJSOverlayView } from "@googlemaps/three";

let map: google.maps.Map;

const mapOptions = {
  tilt: 0,
  heading: 0,
  zoom: 18,
  center: { lat: 35.6594945, lng: 139.6999859 },
  mapId: "15431d2b469f209e",
  // disable interactions due to animation loop and moveCamera
  disableDefaultUI: true,
  gestureHandling: "none",
  keyboardShortcuts: false,
};

function initMap(): void {
  const mapDiv = document.getElementById("map") as HTMLElement;

  map = new google.maps.Map(mapDiv, mapOptions);

  const scene = new Scene();

  const directionalLight = new DirectionalLight(0xffffff, 1);
  
  //directionalLight.shadow.bias = - 0.0001;
  
  directionalLight.castShadow = true;
  directionalLight.shadow.mapSize = new Vector2(1024, 1024);


  directionalLight.position.set(0, 100, 0);
  const shadowCameraSize = 1000;
  directionalLight.shadow.camera.left = -shadowCameraSize;
  directionalLight.shadow.camera.right = shadowCameraSize;
  directionalLight.shadow.camera.top = shadowCameraSize;
  directionalLight.shadow.camera.bottom = -shadowCameraSize;
  
  
  scene.add(directionalLight);
  let planeGeom = new PlaneGeometry(100, 100);
  let planeMaterial = new MeshPhongMaterial({ color: 0xffffff });
  let plane = new Mesh(planeGeom, planeMaterial);
  plane.rotation.x = MathUtils.degToRad(-90);
  let planeGeom2 = new PlaneGeometry(100, 100);
  let planeMaterial2 = new MeshPhongMaterial({ color: 0xffffff });
  let plane2 = new Mesh(planeGeom2, planeMaterial2);
  plane2.rotation.x = MathUtils.degToRad(-90);
  plane2.position.y = 40;
  plane2.position.z = 40;
  
  
  plane.castShadow = true;
  plane.receiveShadow = true;
  plane2.castShadow = true;
  plane2.receiveShadow = true;
  
  
  scene.add(plane);
  scene.add(plane2);

  // Load the model.
  const loader = new GLTFLoader();
  const url =
    "https://raw.githubusercontent.com/googlemaps/js-samples/main/assets/pin.gltf";

  loader.load(url, (gltf) => {
    gltf.scene.scale.set(10, 10, 10);
    gltf.scene.rotation.x = Math.PI / 2;
    scene.add(gltf.scene);

    let { tilt, heading, zoom } = mapOptions;

    const animate = () => {
      if (tilt < 67.5) {
        tilt += 0.5;
      } else if (heading <= 360) {
        heading += 0.2;
        zoom -= 0.0005;
      } else {
        // exit animation loop
        return;
      }

      map.moveCamera({ tilt, heading, zoom });

      requestAnimationFrame(animate);
    };

    requestAnimationFrame(animate);
  });

  new ThreeJSOverlayView({
    map,
    scene,
    anchor: { ...mapOptions.center, altitude: 70 },
  });
}
export { initMap };

`

**Comment by jpoehnelt** [comment]
Can you file a feature request for this? https://issuetracker.google.com/issues/new?component=188853&template=787814

**Comment by YosanAI** [comment]
Sure. can I make the feature request more general like getting access to the light source used on the map to then cast and receive shadows from buildings on the map? map objects should also cast/receive shadows from other map objects.

**Comment by YosanAI** [comment]
I believe this was possible with the Game Map API that is now discontinued.
