### ISSUE TITLE
Objects noticeably jitter / anchor issue

### ISSUE THREAD

**Issue by MadOPcode** [googlemaps/js-three#189]
While using @googlemaps/three I've noticed that 3D objects rendered onto the map using `ThreeJSOverlayView` jitter.
https://drive.google.com/file/d/1uacSEtHdXIxr5tLRQtKwhRqog6vY_w5T/view?usp=sharing
Apparently this is related to the fact that the objects and the camera are too far from the world's origin. So when the vertices' positions are computed by the shader there's not enough fp precision (see `src/fp-precision` directory in the linked repo).
So I tried moving the world's origin closer to the camera for which the `anchor` property of `ThreeJSOverlayView` exists it seems. And indeed the jittering of the objects in this case is not observed (see `src/rel-coords` directory in the linked repo). However the coordinates (computed using `latLngToVector3Relative`) at which the objects are rendered are way off (except for the object which is located exactly at the anchor's position). Compare positions of red boxes which are not in the initial center in `fp-precision` and `rel-coords` in the linked repo.
So how to go about these issues?

#### Environment details

Windows 10 x64, Chrome (latest)

#### Steps to reproduce

Just clone the repo linked below and follow the README.

#### Code example

Here's the repo with the described issues:
https://github.com/MadOPcode/googlemaps-threejsoverlayview-issues

**Comment by jpoehnelt** [comment]
Added a test case for `latLngToVector3Relative` in #190 using the two coords but it returns a vector within 1 meter (when  compared to an external source I used to project the coordinates from epsg:4326 to epsg:3857).

Given the location, this makes me think there is a scaling issue going on.

![rel-coords](https://user-images.githubusercontent.com/3392975/140995543-48358a40-3524-4b74-b95d-dee3ac113134.png)

**Comment by jpoehnelt** [comment]
Added grid to confirm.

```js
scene.add(new GridHelper(2500, 10));
```
Which corresponds to:

```
relative: {
      x: 567.288771994994,
      y: -254.89467016328126,
    },
```
![image](https://user-images.githubusercontent.com/3392975/141000700-01ca4412-892e-4545-a577-2ffcdc6edfc7.png)

Probably need to make a reproducible example that doesn't use this library and see if it is caused by something in: 

```js
onDraw(
    gl: WebGLRenderingContext,
    transformer: google.maps.CoordinateTransformer
  ): void {
    const { lat, lng, altitude } = this.anchor;

    this.camera.projectionMatrix.fromArray(
      transformer.fromLatLngAltitude(
        { lat, lng },
        altitude,
        this.rotation,
        this.scale
      )
    );

    gl.disable(gl.SCISSOR_TEST);

    this.requestRedraw();
    this.renderer.render(this.scene, this.camera);

    // reset state using renderer.resetState() and not renderer.state.reset()
    this.renderer.resetState();
  }
```

or is a bug in the transformer (maybe??)

**Comment by MadOPcode** [comment]
@jpoehnelt should I file a bug for Maps Javascript API to the issue tracker?

**Comment by jpoehnelt** [comment]
Yeah, please do and add the link back here.

**Comment by jpoehnelt** [comment]
Reported in public tracker at https://issuetracker.google.com/issues/206669734

**Comment by teledemic** [comment]
FWIW I get a crazy amount of jitter even on the official basic example, when zoomed in closely to the box and rotating the camera (in chrome). The vertices on the box move a little even when the camera isn't moving. Zoomed out is fine.
https://googlemaps.github.io/js-three/public/basic/

https://user-images.githubusercontent.com/4006396/145103621-88f894ab-dfb9-4c06-874f-9a161aceb09e.mov

**Comment by jpoehnelt** [comment]
@teledemic Can you create a reproducible example without this library and post to https://issuetracker.google.com/issues/206669734.

**Comment by teledemic** [comment]
Hm probably not. I'm using this library since I don't know enough about doing it without.

FWIW I switched to this library from https://github.com/ubilabs/threejs-overlay-view because that seems to have been abandoned - that library had other coordinate problems, but did not have the jitter.

**Comment by teledemic** [comment]
I do not believe this issue is fixed. I still see the jitter in my project, and https://googlemaps.github.io/js-three/public/basic/ still shows the same jitter & deforming of the box as in the video above.

**Comment by squishyu** [comment]
Any updates on this issue? I'm trying to use this library in a project and I still get the jitter problem. The issue gets worse the further I go from the world origin (0, 0, 0).

**Comment by TimBarham** [comment]
I'm no expert on this, but here was how I was able to solve the jittering issue:
1. Choose an origin close to my view (rather than 0,0,0). For example, I use the center of my current map view.
2. Fix `latLngToMeters()` to use the radius of the earth at the current origin. I calculate that radius when the origin is set/changed:

``` js
        let h = Math.sin(MathUtils.degToRad(this.origin.lat)) * EARTH_RADIUS;
        this.originRadius = Math.round(Math.sqrt(Math.pow(EARTH_RADIUS, 2) - Math.pow(h, 2)));
```

**Comment by usefulthink** [comment]
This should be finally solved in the next major release coming in a couple weeks.
The solution is to a) use an anchor point close to where the action is happening (avoid x/y values in the millions of meters) and  b) use the following to compute x/y/z values from geo-coordinates:

https://github.com/googlemaps/js-three/blob/ef635d12cf853a2797e5f17f31bb2bfcc1671f46/src/util.ts#L56-L83
