### ISSUE TITLE
Unable to extend ThreeJSOverlayView

### ISSUE THREAD

**Issue by YosanAI** [googlemaps/js-three#219]
I am trying to extend the class like this:

`let threeOverlay=new CustomeOverlay({
        map,
        scene,
        anchor: { ...mapOptions.center, altitude: 0 },
    });`

`export class CustomeThreeOverlay extends ThreeJSOverlayView{
constructor(options: ThreeJSOverlayViewOptions){
    super(options)
}`

however, this doesn't work and doesn't throw any error. 
the following works when i am not using `super`.
 
`export class CustomeThreeOverlay extends ThreeJSOverlayView{
constructor(options: ThreeJSOverlayViewOptions){
}`

but i want to pass the options to `ThreeJSOverlayView`

by working, i meant console logs after `new customeOverlay` . if super is used in the constructor as shown above, the console logs doesnt even work:

`let threeOverlay=new CustomeOverlay({
        map,
        scene,
        anchor: { ...mapOptions.center, altitude: 0 },
    }); console.log("This doesnt get logged")`

**Comment by YosanAI** [comment]
I fixed this by changing the target tsconfig from es5 to es6. but I want to use es5 because I want it to work on most browsers

**Comment by jpoehnelt** [comment]
Closing, please reopen with reproducible example if possible.
