### ISSUE TITLE
Rendering on demand

### ISSUE THREAD

**Issue by YosanAI** [googlemaps/js-three#242]
i want to render scene only when things changed. I have tried extending the onDraw() function like this but the scene only gets rendered for a few frames and then disappers.

` onDraw(
    gl: WebGLRenderingContext,
    transformer: google.maps.CoordinateTransformer
  ): void {
    const { lat, lng, altitude } = this.anchor;

    this.camera.projectionMatrix.fromArray(
      transformer.fromLatLngAltitude(
        { lat, lng },
        altitude,
        this.rotation,
        this.scale
      )
    );
    if(!this.camera.projectionMatrix.equals(this.oldCameraMatrix)){
      this.oldCameraMatrix.copy(this.camera.projectionMatrix);
      this.canRender=true;
      console.warn("cameraprojectionmatrix changed");
    }
    else{
      this.canRender=false;
    }
    gl.disable(gl.SCISSOR_TEST);

    console.log("Render loop");
    
    this.requestRedraw();
    if(this.canRender){
     
      console.log("Rendering on demand");
      
      this.renderer.render(this.scene, this.camera);
      this.protectedBox.position.y+=0.01;
      this.canRender=false;
    
    
   
    
      }
       // reset state using renderer.resetState() and not renderer.state.reset()
      this.renderer.resetState();
  }
  renderOndemand(){
    this.requestRedraw();
    //this.renderer.render(this.scene, this.camera);
    this.canRender=true;
    
  }
}`

**Comment by jpoehnelt** [comment]
> if(!this.camera.projectionMatrix.equals(this.oldCameraMatrix)){

There is probably some state being cleared internally that requires the rerender?? Have you tried moving the resetState call into the if branch?
