### ISSUE TITLE
Renderer does not clip all objects outside of viewport

### ISSUE THREAD

**Issue by crunchwrap89** [googlemaps/js-three#436]
Objects that are added to the scene of the WebGLOverlay are being rendered by the renderer even when the objects are outside of the current viewport.
This has very bad effect on the performance of the map when having objects scattered all over the world. The renderer should not do any drawcalls to objects outside of the viewport.
Currently objects are being clipped between zoomlevel 1-4 but not between zoomlevel 4-22.

For example: Half of the maps worldspace are always being rendered even if on zoomLevel 22.

#### Environment details
Chrome @latest
"@googlemaps/three": "^3.0.3",
Node 16.15.0

#### Steps to reproduce

  1. Clone repo from  https://github.com/crunchwrap89/googlemaps-three-frustumculling
  2. follow instructions in the readme.md

#### Code example

see repo above and read readme.md

**Comment by amuramoto** [comment]
Thanks for reporting and for the repro! My initial thought is that this is expected behavior where we are pre-rendering tiles outside the viewport, but we'll take a look at whether there's potential for performance improvement here.

**Comment by crunchwrap89** [comment]
> Thanks for reporting and for the repro! My initial thought is that this is expected behavior where we are pre-rendering tiles outside the viewport, but we'll take a look at whether there's potential for performance improvement here.

Hi,
Thanks for taking a look Alex.
Let me know if you need any further information from me to investigate.

//Marcus
