### ISSUE TITLE
@googlemaps/js-three latLngToVector3 inconsistent on different hemispheres 

### ISSUE THREAD

**Issue by shannonhobby** [googlemaps/js-three#51]
I've noticed inconsistencies with the latLngToVector3 function based on which hemisphere the coordinates are on. Manipulating the Threejs Scene rotation seems to fix this issue, but I was just wondering if this is expected behavior or not? 

#### Steps to reproduce / Code example

In this code example I placed a sphere at the coordinates of NYC and the coordinates of Sydney, Australia. As you can see in the example the sphere for Australia lands on Sydney just fine but the sphere for NY ends up in the middle of the ocean. To fix this you need to add a negative sign to scene.rotation.x and add the line scene.rotation.z = Math.PI.  Unfortunately this makes it so that the Australian sphere is no longer in the correct location. In my code I simply have an if statement that changes these parameters depending on the latitude and longitude, but I'm worried that there may be other inconsistencies that I haven't run into just yet.

https://codesandbox.io/s/vibrant-flower-z9tyt?file=/src/index.ts

Please let me know if you need anymore details!

**Comment by jpoehnelt** [comment]
Hi @shannonhobby 

I added a test in #52 and example and am unable to recreate the issue. This is using the `ThreeJSoverlayView` class from this library with the default scene rotation applied, `scene.rotation.x = Math.PI / 2;`.

![Screen Shot 2021-07-19 at 4 54 50 PM](https://user-images.githubusercontent.com/3392975/126237844-485a5bf2-5468-431a-b983-a21ab50582c1.png)

**Comment by shannonhobby** [comment]
Hi Justin!

Thanks for looking into it. Here's a version of my sandbox using ThreeJSOverlayView and the default rotation: https://codesandbox.io/s/vibrant-flower-z9tyt?file=/src/index.ts. New York City is in the right place this time but Australia is not. 

![image](https://user-images.githubusercontent.com/43319740/126543638-43ab4ad3-8ec6-4a03-b1c8-10a49f742ae3.png)

**Comment by shannonhobby** [comment]
New development: This is the outcome when using latLngToVector3Relative on all points of latitude longitude (-90, 90 and -180, 180). ![image](https://user-images.githubusercontent.com/43319740/126554755-8721ec66-6421-4216-9875-40d66fb21ff0.png)
It only appears on a portion of the screen, is this expected behavior? Here's the code sandbox for this specific example: https://codesandbox.io/s/vibrant-flower-z9tyt?file=/src/index.ts
