### ISSUE TITLE
Manipulate tiles

### ISSUE THREAD

**Issue by crunchwrap89** [googlemaps/js-three#789]
It would be super cool to be able to access the 3d tiles on the map and manipulate them on runtime.
That would be a complete game changer. 

Some things I would do if that feature was available: 
- Add a physics engine such as ammo.js so 3d objects cannot pass through buildings.
- Animate the buildings in sync with music.
- Add shadows to the buildings
- Add Elevation to the map to create hills and valleys and adjust the elevation for the 3d tiles accordingly.

**Comment by usefulthink** [comment]
I'd love that as well, but as it is right now, there's no way we can make the data accessible to the outside. That would need something like a 3d tileset (essentially, what the photorealistic 3d-tiles are, but with simplified geometries).

**Comment by crunchwrap89** [comment]
okay, thanks for looking into it
