### ISSUE TITLE
Render with WebGPURenderer

### ISSUE THREAD

**Issue by crunchwrap89** [googlemaps/js-three#860]
WebGPU is now generally available in newer versions of chrome and firefox and is also supported with Three.js with a new renderer ( WebGPURenderer ). 
It would be great if we could make use of this in the WebGLOverlayView, or perhaps a new WebGPUOverlayView (?). 

We could drastically improve the performance when rendering complex 3d scenes on the map. <3

I guess this is something that needs to be developed within the google maps js api as well?. 
I am curious to hear if its already being worked on and when it might be publicly available? :)

**Comment by usefulthink** [comment]
Hi there,

yeah. That is going to take a while... 
WebGPU would make it a lot easier to deal with sharing the rendering context, but it would first need a google-maps API version based on WebGPU, and I wouldn't exactly hold my breath on that. It might (and probably will) happen at some point, but it's impossible to tell from the outside if that is something being looked at or pursued by the maps engineering team.
