### ISSUE TITLE
Combining with google.maps.Polygon

### ISSUE THREAD

**Issue by kevinsimper** [googlemaps/js-three#94]
When I combined the use of ThreeJSOverlayView, just following the basic tutorials, it appears like the Overlay that google.maps.Polygon is drawn is messed with.

You can see the overlay does not follow the map
![2021-09-16 02 46 34](https://user-images.githubusercontent.com/1126497/133531549-ae313f63-4488-43f7-add4-f0fe19e5e376.gif)

and the code to add the gltf is the example:
```
const scene = new Scene();
      const ambientLight = new AmbientLight(0xffffff, 0.75);

      scene.add(ambientLight);

      const directionalLight = new DirectionalLight(0xffffff, 0.25);

      directionalLight.position.set(0, 10, 50);
      scene.add(directionalLight);

      const center = map.getCenter();
      if (!center) return;
      new ThreeJSOverlayView({
        map,
        scene,
      });

      const loader = new GLTFLoader();
      const url =
        "https://raw.githubusercontent.com/googlemaps/js-samples/master/assets/pin.gltf";

      loader.load(url, (gltf) => {
        gltf.scene.scale.set(100, 100, 100);
        gltf.scene.position.copy(
          latLngToVector3({ lat: 55.6832338, lng: 12.5819998 })
        );
        gltf.scene.position.setY(500);
        gltf.scene.rotation.x = Math.PI / 2;
        scene.add(gltf.scene);
        console.log(gltf);
      });
```

If new `ThreeJSOverlayView({
        map,
        scene,
      });` is commented out, then the problem disappears

![2021-09-16 02 48 56](https://user-images.githubusercontent.com/1126497/133531697-28937164-92b6-4faa-966f-f8ef1053046d.gif)

The code to draw the polygons are just this
```
const path = new google.maps.Polygon({
        paths: line,
        geodesic: true,
        strokeColor: color,
        strokeOpacity: 1.0,
        strokeWeight: 2,
        fillColor: color,
        fillOpacity: 0.1,
      });
      path.setMap(map);
```

and the map is initialized with mapid
`{ zoom: 12, mapId: mapid, heading: 0, tilt: 45 }` and this script `https://maps.googleapis.com/maps/api/js?key=${apiKey}&v=beta&callback=initMap`;

and important detail is also, if I remove all old `new google.maps.Polygon`, then the `ThreeJSOverlayView` works great.

![2021-09-16 02 56 04](https://user-images.githubusercontent.com/1126497/133532239-106e199c-3f2c-4d93-a8c9-973501a92c89.gif)

**Comment by jpoehnelt** [comment]
@kevinsimper 

Thanks for reporting! Would you mind opening this on https://issuetracker.google.com/issues/new?component=188853&template=788207?

I think this is likely to be an internal issue. Please post the issue link here so others can follow along if desired. I'll keep an eye on it and make sure it gets to the correct team.

**Comment by kevinsimper** [comment]
@jpoehnelt Thank you! 

I have created it here: https://issuetracker.google.com/issues/200065975

**Comment by kevinsimper** [comment]
Just tested and the problem still persists in google.maps.version '3.47.1-beta'

Made a reproducable case here

https://codesandbox.io/s/unruffled-yalow-7c7dk?file=/src/index.ts

**Comment by amuramoto** [comment]
closing this since it is being handled as an API issue in the [issuetracker](https://issuetracker.google.com/issues/200065975)

Hi Kevin! =)
